spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogvuespringboot?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      validation-query: SELECT 1
      validation-query-timeout: 2000

    type: com.alibaba.druid.pool.DruidDataSource


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.live.blogvuespringboot.model.pojo
  mapper-locations: classpath:com.live.blogvuespringboot.mapper/*.xml

### jwt
jwt:
  ###过期时间 s数432000 5天
  time: 432000
  ###安全密钥
  secret: "BlogKUDXSecret"
  ###token前缀
  prefix: "Bearer "
  ###http头key
  header: "Authorization"


  ucloud:
    ufile:
      public-key: "TOKEN_efc33c0d-41c1-4695-8a8a-45f5c5dffdbd"
      private-key: "9ccfedb9-bf53-490e-8222-25a2c0e97c22"
      bucket-name: "yiyezi"
      region: "cn-gd"
      suffix: "ufileos.com"
      expires: 315360000


server:
  port: 8081

