spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_2?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      validation-query: SELECT 1
      validation-query-timeout: 2000
    driver-class-name: com.alibaba.druid.proxy.DruidDriver


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.live.blogvuespringboot.model.pojo
  mapper-locations: classpath:com.live.blogvuespringboot.mapper/*.xml

### jwt
jwt:
  ###过期时间 s数432000 5天
  time: 432000
  ###安全密钥
  secret: "BlogKUDXSecret"
  ###token前缀
  prefix: "Bearer "
  ###http头key
  header: "Authorization"


server:
  port: 8081

